1. Determining length of a matrix/vector.

In [17]:
import numpy as np
A = np.matrix([[1,2],[3,4],[5,6]])
len(A)

3

2. Add B as the fourth row of A to create C.

In [5]:
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

B = np.array([10, 11, 12])

C = np.vstack((A, B))
C

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

3. Create D from rows 2, 3, 4 and columns 3, 4 of C.

In [6]:
D = C[1:4, 2:4]

D

array([[ 6],
       [ 9],
       [12]])

4. Transpose D to create E.

In [7]:
E = D.T

E

array([[ 6,  9, 12]])

5. Check the size of E.

In [8]:
E.shape

(1, 3)

6. Create equally spaced vectors.

In [9]:
v1 = np.linspace(1, 10, 5)
v2 = np.linspace(0, 1, 4)

v1, v2

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]),
 array([0.        , 0.33333333, 0.66666667, 1.        ]))

7. Find the max and min in each column of A.

In [10]:
max_cols = np.max(A, axis=0)
min_cols = np.min(A, axis=0)

max_cols, min_cols

(array([7, 8, 9]), array([1, 2, 3]))

8. Find the max and min in each row of A.

In [11]:
max_rows = np.max(A, axis=1)
min_rows = np.min(A, axis=1)

max_rows, min_rows

(array([3, 6, 9]), array([1, 4, 7]))

9. Calculate mean and sum in each column and row of A.

In [12]:
mean_cols = np.mean(A, axis=0)
sum_cols = np.sum(A, axis=0)

mean_rows = np.mean(A, axis=1)
sum_rows = np.sum(A, axis=1)

mean_cols, sum_cols, mean_rows, sum_rows


(array([4., 5., 6.]),
 array([12, 15, 18]),
 array([2., 5., 8.]),
 array([ 6, 15, 24]))

10. Create random matrices F and G.

In [15]:
F = np.random.rand(3, 3)
G = np.random.rand(3, 3)

F,G

(array([[7.41635780e-01, 2.70070892e-01, 2.28374962e-01],
        [6.06942719e-01, 3.98980292e-05, 9.33707975e-01],
        [2.93827097e-01, 7.30691945e-01, 1.50772001e-01]]),
 array([[0.15762159, 0.14392759, 0.0893236 ],
        [0.88615927, 0.844756  , 0.28868451],
        [0.80215289, 0.38678441, 0.30216254]]))

11. Perform scalar multiplication, addition, subtraction, and element-wise
multiplication on F and G.

In [29]:
scalar = 2

scalar_mult = scalar * F
addition = F + G
subtraction = F - G
elementwise_mult = F * G

scalar_mult, addition, subtraction, elementwise_mult


(array([[0.38915506, 1.75586841, 0.75590338],
        [0.21347871, 1.91858712, 1.82765692],
        [0.13263369, 1.35534342, 0.62194282]]),
 array([[0.20671288, 0.99780995, 0.70468916],
        [1.10232314, 1.21260796, 1.69046779],
        [0.22179209, 0.89651595, 0.56042781]]),
 array([[ 0.18244218,  0.75805846,  0.05121421],
        [-0.88884442,  0.70597916,  0.13718913],
        [-0.0891584 ,  0.45882748,  0.06151501]]),
 array([[0.00236127, 0.10524302, 0.12349098],
        [0.10626797, 0.24300288, 0.70971512],
        [0.01031063, 0.14830455, 0.07757381]]))

12. Check the size of F and A, then perform matrix multiplication if
dimensions are compatible.

In [36]:
F.shape, A.shape

if F.shape[1] == A.shape[0]:
    matrix_mult = np.dot(F, A)
    print(matrix_mult)
else:
    print("Matrix multiplication not possible due to incompatible dimensions")

[[ 6.35197616  7.80243958  9.252903  ]
 [10.34071282 12.3205742  14.30043557]
 [ 4.95380357  6.00876354  7.0637235 ]]


### Task 13: Generate Special Matrices

1. Create a **3×3 identity matrix**.
2. Create a **5×3 zero matrix** and a **4×2 one matrix**.
3. Create a **diagonal matrix** `S` with diagonal elements `[1, 2, 7]`.
4. Extract the **diagonal elements** from a randomly generated **6×6 matrix**.
5. Create a **sparse diagonal matrix** and convert it into a **dense matrix**.


In [40]:
from scipy.sparse import diags

I = np.eye(3)
Z = np.zeros((5, 3))
O = np.ones((4, 2))
S = np.diag([1, 2, 7])
random_matrix = np.random.rand(6, 6)
diag_elements = np.diag(random_matrix)
sparse_diag = diags([[1, 2, 7]], [0], shape=(3, 3)).toarray()

I, Z, O, S, diag_elements, sparse_diag

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 7]]),
 array([0.90101472, 0.98450454, 0.98242633, 0.38624709, 0.18779002,
        0.12543064]),
 array([[1., 0., 0.],
        [0., 2., 0.],
        [0., 0., 7.]]))