In [4]:
import numpy as np

A = np.array([[3, 1, -1],
              [2, 4, 1],
              [1, -1, 3]])

b = np.array([[4], 
              [10], 
              [5]])

In [5]:
x = np.linalg.solve(A, b)


residual = np.dot(A, x) - b

print("Solution x:\n", x)
print("Residual r:\n", residual)

Solution x:
 [[1.425]
 [1.375]
 [1.65 ]]
Residual r:
 [[-4.44089210e-16]
 [ 1.77635684e-15]
 [-8.88178420e-16]]


In [8]:
import scipy.linalg
P, L, U = scipy.linalg.lu(A)

x1 = np.linalg.solve(A,b)
err1 = np.dot(A,x1) - b
print("Permutation Matrix")
print(P)
print("Matrix L")
print(L)
print("Matrix U")
print(U)
print("Solution vector")
print(x1)
print("Error vector")
print(err1)

Permutation Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matrix L
[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 0.33333333 -0.4         1.        ]]
Matrix U
[[ 3.          1.         -1.        ]
 [ 0.          3.33333333  1.66666667]
 [ 0.          0.          4.        ]]
Solution vector
[[1.425]
 [1.375]
 [1.65 ]]
Error vector
[[-4.44089210e-16]
 [ 1.77635684e-15]
 [-8.88178420e-16]]


In [9]:
y = np.linalg.lstsq(A,b,rcond=None)[0]
print("Solution Vector")
print(y)

Solution Vector
[[1.425]
 [1.375]
 [1.65 ]]


In [10]:
A_inv = np.linalg.inv(A)
x2 = np.dot(A_inv,b)
r2 = np.dot(A,x2) - b
err2 = x2 - x
print("Solution vector")
print(x2)
print("Residual vector")
print(r2)
print("Error vector")
print(err2)

Solution vector
[[1.425]
 [1.375]
 [1.65 ]]
Residual vector
[[ 0.0000000e+00]
 [ 0.0000000e+00]
 [-8.8817842e-16]]
Error vector
[[ 2.22044605e-16]
 [-2.22044605e-16]
 [ 0.00000000e+00]]


In [11]:
def rref(A):
    """ 
    Computes the reduced row echelon form (RREF) of a matrix A.
    Parameters:
    A : numpy.ndarray
    Input matrix of shape (m, n)

    Returns:
    R : numpy.ndarray
    Reduced row echelon form of matrix A
    """ 
    A = A.astype(float)
    m, n = A.shape
    load = 0
    for r in range(m):
        if load >= n:
            break
        if A[r, load] == 0:
            for i in range(r + 1, m):
                if A[i, load] != 0:
                    A[r, i] = A[i], r
                    break
        if A[r, load] != 0:
            A[r] = A[r] / A[r, load]
            for i in range(m):
                if i != r:
                    A[i] = A[i] - A[i, load] * A[r]
            load += 1
    return A

# Compute reduced row echelon form of [A | b]
print(A)
print(b)
C = np.hstack((A, b.reshape(-1, 1)))
print("[A:B] vector", C)
R = rref(C)

# Extract solution vector x3 from the RREF matrix
x3 = R[:, -1]

# Calculate residuals
r3 = np.dot(A, x3) - b
err3 = x - x3

print("\nSolution vector x3 (from RREF):")
print(x3)
print("\nResidual vector r3 (from RREF):")
print(r3)
print("\nError vector err3 (difference between x and x3):")
print(err3)

[[ 3  1 -1]
 [ 2  4  1]
 [ 1 -1  3]]
[[ 4]
 [10]
 [ 5]]
[A:B] vector [[ 3  1 -1  4]
 [ 2  4  1 10]
 [ 1 -1  3  5]]

Solution vector x3 (from RREF):
[1.425 1.375 1.65 ]

Residual vector r3 (from RREF):
[[-8.88178420e-16  6.00000000e+00  1.00000000e+00]
 [-6.00000000e+00  1.77635684e-15 -5.00000000e+00]
 [-1.00000000e+00  5.00000000e+00  0.00000000e+00]]

Error vector err3 (difference between x and x3):
[[ 0.00000000e+00  5.00000000e-02 -2.25000000e-01]
 [-5.00000000e-02  0.00000000e+00 -2.75000000e-01]
 [ 2.25000000e-01  2.75000000e-01 -2.22044605e-16]]


In [12]:
import time
import numpy as np

# Method 1: Solve using solve operator
start_time = time.time()
x1 = np.linalg.solve(A, b)
end_time = time.time()
time_backslash = end_time - start_time

# Method 2: Solve using matrix inverse
start_time = time.time()
x2 = np.linalg.inv(A) @ b
end_time = time.time()
time_inv = end_time - start_time

# Method 3: Solve using reduced row echelon form (rref)
start_time = time.time()
C = np.hstack((A, b.reshape(-1, 1)))
R = rref(C)
x3 = R[:, -1]
end_time = time.time()
time_rref = end_time - start_time

# Print the solution vectors and computational times
print("\nSolution vector x1 (using backslash operator):")
print(x1)

print("\nSolution vector x2 (using matrix inverse):")
print(x2)

print("\nSolution vector x3 (using reduced row echelon form):")
print(x3)

print("\nComputational times:")
print(f"Backslash operator: {time_backslash} seconds")
print(f"Matrix inverse: {time_inv} seconds")
print(f"Reduced row echelon form (rref): {time_rref} seconds")


Solution vector x1 (using backslash operator):
[[1.425]
 [1.375]
 [1.65 ]]

Solution vector x2 (using matrix inverse):
[[1.425]
 [1.375]
 [1.65 ]]

Solution vector x3 (using reduced row echelon form):
[1.425 1.375 1.65 ]

Computational times:
Backslash operator: 0.005710124969482422 seconds
Matrix inverse: 0.0007648468017578125 seconds
Reduced row echelon form (rref): 0.00021696090698242188 seconds
